
spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
  r2dbc:
    driver-class-name: org.postgresql.Driver
    url: r2dbc:postgresql://localhost:5432/ProductService
    username: postgres
    password: Vaifery111

  application:
    name: product

server:
  port: 7002



